services:
  lokal-server:
    network_mode: "host"
    image: citatoji/lokal-server:latest
    restart: unless-stopped
    environment:
      - TUNNEL_SERVER_BIND_HOST=0.0.0.0
      - TUNNEL_SERVER_BIND_PORT=8080
      - TUNNEL_SERVER_JWT_SECRET=
      - TUNNEL_SERVER_ENCRYPTION_KEY=
      - VHOST_HTTP_HOST=0.0.0.0
      - VHOST_HTTP_PORT=80
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --include-stopped --cleanup --revive-stopped
    restart: unless-stopped